#SPDX-License-Identifier: MIT-0
---
# tasks file for add_users
- name: Add users to the linux host
  ansible.builtin.user:
    name: "{{item}}" 
    state: present
  become: true
  # vars:
  #   new_user: test1
  loop: "{{new_user}}"
    # - test1
    # - test2
    # - test3