---
- name: Fetch current weather data for Paris, Texas
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get forecast data for Paris, Texas
      ansible.builtin.uri:
        url: "https://api.weather.gov/gridpoints/FWD/136,142/forecast"
        method: Get
        validate_certs: yes
      register: forecast_response

    - name: Display detailed forecast data
      ansible.builtin.debug:
        var: forecast_response.json

    # - name: Print chance of rain tomorrow
    #   ansible.builtin.debug:
    #     msg: >-
    #       Tomorrow chance of rain(percentage):
    #       Morning: {{(forecast_response.json.properties.periods | selectattr('number', 'equalto', 3) | list).0.probabilityOfPrecipitation.value | default(0, true)}} and
    #       Afternoon: {{(forecast_response.json.properties.periods | selectattr('number', 'equalto', 4) | list).0.probabilityOfPrecipitation.value | default(0, true)}}