---
- name: A simple playbook to add users to a lunix host
  hosts: aws_instances
  gather_facts: false
  # vars_files:
  #   - file/users.yml
  vars:
    # ignore_users:
      # - root
      # - test1
    new_user: 
      - test1
      - test2
      - test3

  tasks:
    - name: Add users to the linux host
      # when: item not in ignore_users | default("alwaysworks")
      when: item not in ignore_users | default(omit) #if the variable is undefined. it will redact the check
      ansible.builtin.user:
        name: "{{item}}" 
        state: present
      become: true
      # vars:
      #   new_user: test1
      loop: "{{new_user}}"
        # - test1
        # - test2
        # - test3