---
- name: A simple playbook to add users to a lunix host
  hosts: aws_instances
  gather_facts: false
  # vars_files:
  #   - file/users.yml
  vars:
    new_user: 
      - test1
      - test2
      - test3

  tasks:
    - name: Add users to the linux host
      ansible.builtin.user:
        name: "{{item}}" 
        state: present
      become: true
      # vars:
      #   new_user: test1
      loop: "{{new_user}}"
        # - test1
        # - test2
        # - test3