---
- name: A simple playbook to add users to a lunix host
  hosts: aws_instances
  gather_facts: false
  vars:
  tasks:
    - name: Add users to the linux host
      ansible.builtin.user:
        name: test1
        state: present
      become: true