---
- name: A simple playbook to add users to a lunix host
  hosts: aws_instances
  gather_facts: false
  vars_files:
    - file/users.yml
  vars:
    # new_user: test1

  tasks:
    - name: Add users to the linux host
      ansible.builtin.user:
        # name: "{{new_user}}" # can provide the variables in CLI, using -e after inventory
        state: present
      become: true
      # vars:
      #   new_user: test1