---
- name: Vaulting example
  hosts: aws_instances
  gather_facts: false
  become: true
  vars_files:
    - files/secrets.yml #encrypted file

  tasks:
    - name: Display the super_secret variable
      ansible.builtin.debug:
        var: super_secret