---
- name: Quick webserver install and config
  hosts: aws_instances
  gather_facts: false
  become: true
  tasks:
    - name: Install apache webserver
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true # if i reboot it, it will make sure that services are started

    - name: Wrute a simple index.html file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "<h1> Hello World! </h1>"
        create: true #if the file doens't exist, create it